version: '3.4'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: cs-main-server
    restart: unless-stopped

    depends_on:
      - mariadb

    environment:
      GAMESERVER: csserver
      LGSM_GITHUBUSER: GameServerManagers
      LGSM_GITHUBREPO: LinuxGSM
      LGSM_GITHUBBRANCH: master

    volumes:
      - ./server/serverfiles:/home/linuxgsm/serverfiles
      - ./server/log:/home/linuxgsm/log
      - ./server/configs-lgsm:/home/linuxgsm/lgsm/config-lgsm/csserver
    ports:
      - "${FORWARD_SERVER_PORT:-27015}:27015/tcp"
      - "${FORWARD_SERVER_PORT:-27015}:27015/udp"
    networks:
      - default

  mariadb:
    image: mariadb:latest
    container_name: cs-main-mariadb
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-g4nfhk4hjgf4kfg4}'
      MYSQL_DATABASE: '${DB_DATABASE:-csserver}'
      MYSQL_USER: '${DB_USERNAME:-csserver}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-qwerty}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - default

  fastdl:
    build:
      context: ./fastdl
      dockerfile: ./Dockerfile
    container_name: cs-main-fastdl
    restart: unless-stopped

    depends_on:
      - server

    volumes:
      - ./server/serverfiles/cstrike:/var/www:ro
    ports:
      - '${FORWARD_FASTDL_PORT:-27115}:80'
    networks:
      - default
      
networks:
  default:
    driver: bridge
    
